Added EDA notebook
soumik12345/point-cloud-segmentation pull request #1
Opened 2021-09-30 15:44 UTC by soumik12345

2021-10-01 02:00 UTC, sayakpaul requested changes
Looks good to me with a few comments:

* Add sufficient annotation above the non-trivial code cells. 
* [This notebook](https://www.kaggle.com/kmader/point-cloud-overview) does provide a flexible template to perform basic EDA on point cloud segmentation. We may want to follow that. 
* There seems to be a mismatch in the mapping:

![image](https://user-images.githubusercontent.com/22957388/135553984-715e7500-b30e-4fcb-b5f3-9b2a8bfae965.png)

2021-10-02 02:04 UTC, soumik12345 commented
@sayakpaul fixed the mismatch in mapping, will continue with the EDA.

2021-10-02 03:07 UTC, sayakpaul commented
@soumik12345 things are looking better. Also, try adding the legends in the overlaid plot to make it easier to debug and visualize better.

2021-10-02 04:52 UTC, soumik12345 commented
@sayakpaul , although the 1st point cloud labels are being plotted accurately, the later ones seem to be wrong. Can you please suggest what could be the issue?

2021-10-02 05:47 UTC, sayakpaul commented on pointnet_shapenet.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #5.        point_cloud = np.loadtxt(points_files[0])
</pre><p> </p><p>Why are we loading the same thing again and again inside the loop?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/soumik12345/point-cloud-segmentation/pull/1/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='6'/>

2021-10-02 05:47 UTC, sayakpaul commented on pointnet_shapenet.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #7.        labels = os.listdir(labels_dir)
</pre><p> </p><p>Same. If I am reading it correctly, it's the same thing being loaded iteratively. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/soumik12345/point-cloud-segmentation/pull/1/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='6'/>

2021-10-02 05:47 UTC, sayakpaul commented on pointnet_shapenet.ipynb
> +{
<p>I would also investigate a couple more to see if this inconsistency is largely the case. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/soumik12345/point-cloud-segmentation/pull/1/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='9'/>

2021-10-02 13:56 UTC, soumik12345 commented on pointnet_shapenet.ipynb
> +{
@sayakpaul this was the culprit, fixed it

2021-10-02 13:56 UTC, soumik12345 commented on pointnet_shapenet.ipynb
> +{
Remove this redundancy

2021-10-02 13:57 UTC, soumik12345 commented on pointnet_shapenet.ipynb
> +{
@sayakpaul it was a silly mistake on my part fixed it, there's no inconsistancy.

2021-10-02 16:14 UTC, sayakpaul requested changes
@soumik12345 much better now. 

Here are a few minor suggestions:

* If possible, then add more details (like which labels did you include, homepage link of the ShapeNet dataset, etc.) in the description of the [released dataset](https://github.com/soumik12345/point-cloud-segmentation/releases/tag/v0.1). 
* Add legends in the visualizations. 
* To make it easier for us and also the other users, consider grouping together similar blocks of code and add descriptive comments wherever necessary. Referring to the code cell where data is being prepared. 
* After the data arrays have been prepared consider taking individual elements from them and comment about their shapes, how they are represented, and so on. 

A related question:

I suppose for modeling, `point_clouds` and `point_cloud_labels` are necessary and the rest are for visualization purposes?

2021-10-02 16:30 UTC, soumik12345 commented
> I suppose for modeling, point_clouds, and point_cloud_labels are necessary and the rest are for visualization purposes?

@sayakpaul you are correct.

2021-10-03 08:29 UTC, soumik12345 commented
> If possible, then add more details (like which labels did you include, homepage link of the ShapeNet dataset, etc.) in the description of the released dataset.

@sayakpaul updated the release description.

2021-10-04 04:56 UTC, sayakpaul requested changes
@soumik12345 I still don't see any useful comments or investigation of the arrays formed after their formation. Without that, it's hard for me to understand how you are approaching the preprocessing steps.

The visualizations look amazing with `plotly`.

2021-10-05 01:26 UTC, soumik12345 commented
> After the data arrays have been prepared consider taking individual elements from them and comment about their shapes, how they are represented, and so on.

Hi @sayakpaul , commented about the arrays being generated.

2021-10-05 01:31 UTC, sayakpaul approved these changes
@soumik12345 thank you! 

Since we are now using `test_point_clouds`, therefore, to avoid confusion, I suggest we name the other arrays accordingly. `train_ point_clouds`, for example.

2021-10-05 01:51 UTC, soumik12345 commented
> @soumik12345 thank you!
> 
> Since we are now using `test_point_clouds`, therefore, to avoid confusion, I suggest we name the other arrays accordingly. `train_ point_clouds`, for example.

Hi @sayakpaul , I added a validation split at the end.

2021-10-05 01:55 UTC, soumik12345 commented
@sayakpaul  Let's merge this branch and create a new branch for the dataloader.

2021-10-05 02:00 UTC, merged